[env]
TERM = "xterm-256color"

[font]
# size = 12.5
size = 14
normal.family = "MesloLGM Nerd Font Mono"

[window]
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"
padding.x = 10
padding.y = 10

[colors.primary]
background = "#000000"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
